{"EventId":441733974,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomJsonTypeInfo","Message":"Handling signal on in-process publisher with payload TestSignalWithCustomJsonTypeInfo { SignalPayload = 10 } (Signal ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling signal on in-process publisher with payload TestSignalWithCustomJsonTypeInfo { SignalPayload = 10 } (Signal ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"in-process","TransportRole":"publisher","SignalPayload":"TestSignalWithCustomJsonTypeInfo { SignalPayload = 10 }","SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling signal on {TransportTypeName:l} {TransportRole:l} with payload {@SignalPayload:l} (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
{"EventId":441733974,"LogLevel":"Information","Category":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomJsonTypeInfo","Message":"Handling signal with payload TestSignalWithCustomJsonTypeInfo { SignalPayload = 10 } (Signal ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling signal with payload TestSignalWithCustomJsonTypeInfo { SignalPayload = 10 } (Signal ID: test-message-id, Trace ID: test-trace-id)","SignalPayload":"TestSignalWithCustomJsonTypeInfo { SignalPayload = 10 }","SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling signal with payload {@SignalPayload:l} (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
{"EventId":712209902,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomJsonTypeInfo","Message":"An exception occurred while handling signal after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomJsonTypeInfoHandler.Handle(TestSignalWithCustomJsonTypeInfo signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware\u00601.Execute(SignalMiddlewareContext\u00601 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line FIXED\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware\u00601.Execute(SignalMiddlewareContext\u00601 ctx)\n   at Conqueror.Signalling.SignalPipelineRunner\u00601.\u003C\u003Ec__DisplayClass3_2.\u003CExecute\u003Eb__1(TSignal signal, CancellationToken token) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED","State":{"Message":"An exception occurred while handling signal after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling signal after {ResponseLatency:0.0000}ms (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
{"EventId":712209902,"LogLevel":"Error","Category":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomJsonTypeInfo","Message":"An exception occurred while handling signal on in-process publisher after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomJsonTypeInfoHandler.Handle(TestSignalWithCustomJsonTypeInfo signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware\u00601.Execute(SignalMiddlewareContext\u00601 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line FIXED\n   at Conqueror.Signalling.SignalPipelineRunner\u00601.Execute(IServiceProvider serviceProvider, TSignal initialSignal, ISignalPublisher\u00601 publisher, SignalTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED\n   at Conqueror.Signalling.SignalDispatcher\u00601.Dispatch(TSignal signal, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalDispatcher.cs:line FIXED\n   at Conqueror.Signalling.SequentialSignalBroadcastingStrategy.BroadcastSignal[TSignal](IReadOnlyCollection\u00601 signalHandlerInvocationFns, IServiceProvider serviceProvider, TSignal signal, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SequentialSignalBroadcastingStrategy.cs:line FIXED","State":{"Message":"An exception occurred while handling signal on in-process publisher after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","TransportTypeName":"in-process","TransportRole":"publisher","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling signal on {TransportTypeName:l} {TransportRole:l} after {ResponseLatency:0.0000}ms (Signal ID: {SignalId:l}, Trace ID: {TraceId:l})"}}
