{"@t":"2020-01-01T00:00:00.0000000Z","@m":"Handling signal with payload\n{\n  \"PayloadSub\": 11,\n  \"PayloadBase\": 10\n}\n(Signal ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","SignalPayload":"{\n  \"PayloadSub\": 11,\n  \"PayloadBase\": 10\n}","SignalId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":441733974,"Name":"conqueror-signal"},"SourceContext":"CustomCategory_TestSignalSub"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"An exception occurred while handling signal after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","@l":"Error","@x":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals+TestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalBaseHandler.Handle(TestSignalBase signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line 769\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware`1.Execute(SignalMiddlewareContext`1 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line 51\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware`1.Execute(SignalMiddlewareContext`1 ctx)\n   at Conqueror.Signalling.SignalPipelineRunner`1.<>c__DisplayClass3_2.<Execute>b__1(TSignal signal, CancellationToken token) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line 36","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":712209902,"Name":"conqueror-signal-exception"},"SourceContext":"CustomCategory_TestSignalSub"}
