{"@t":"2020-01-01T00:00:00.0000000Z","@m":"Publishing in-process signal of type '\"TestSignalWithCustomSerializedPayloadType\"' with payload\n{\n  \"Payload\": 10\n}\n(Signal ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","SignalTypeName":"TestSignalWithCustomSerializedPayloadType","SignalPayload":"{\n  \"Payload\": 10\n}","SignalId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":441733974,"Name":"conqueror-signal"},"SourceContext":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomSerializedPayloadType"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"Handling signal of type '\"TestSignalWithCustomSerializedPayloadType\"' with payload\n{\n  \"Payload\": 10\n}\n(Signal ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","SignalTypeName":"TestSignalWithCustomSerializedPayloadType","SignalPayload":"{\n  \"Payload\": 10\n}","SignalId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":441733974,"Name":"conqueror-signal"},"SourceContext":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomSerializedPayloadTypeHandler"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"An exception occurred while handling signal of type '\"TestSignalWithCustomSerializedPayloadType\"' after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","@l":"Error","@x":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals+TestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomSerializedPayloadTypeHandler.Handle(TestSignalWithCustomSerializedPayloadType signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware`1.Execute(SignalMiddlewareContext`1 ctx) in {SolutionDirectory}src/middlewares/logging/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line FIXED\n   at Conqueror.Signalling.SignalPipelineRunner`1.<>c__DisplayClass3_2.<Execute>b__1(TSignal signal, CancellationToken token) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED\n   at Conqueror.Signalling.SignalPipelineRunner`1.Execute(IServiceProvider serviceProvider, TSignal initialSignal, ISignalPublisher`1 publisher, SignalTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED\n   at Conqueror.Signalling.SignalDispatcher`1.Dispatch(TSignal signal, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalDispatcher.cs:line FIXED","SignalTypeName":"TestSignalWithCustomSerializedPayloadType","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":712209902,"Name":"conqueror-signal-exception"},"SourceContext":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomSerializedPayloadTypeHandler"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"An exception occurred while publishing in-process signal of type '\"TestSignalWithCustomSerializedPayloadType\"' after 123.4560ms (Signal ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","@l":"Error","@x":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals+TestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomSerializedPayloadTypeHandler.Handle(TestSignalWithCustomSerializedPayloadType signal, CancellationToken cancellationToken) in {ProjectDirectory}Signalling/LoggingMiddlewareTestSignals.cs:line FIXED\n   at Conqueror.Middleware.Logging.Signalling.LoggingSignalMiddleware`1.Execute(SignalMiddlewareContext`1 ctx) in {SolutionDirectory}src/middlewares/logging/Conqueror.Middleware.Logging/Signalling/LoggingSignalMiddleware.cs:line FIXED\n   at Conqueror.Signalling.SignalPipelineRunner`1.Execute(IServiceProvider serviceProvider, TSignal initialSignal, ISignalPublisher`1 publisher, SignalTransportType transportType, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalPipelineRunner.cs:line FIXED\n   at Conqueror.Signalling.SignalDispatcher`1.Dispatch(TSignal signal, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SignalDispatcher.cs:line FIXED\n   at Conqueror.Signalling.SequentialSignalBroadcastingStrategy.BroadcastSignal[TSignal](IReadOnlyCollection`1 signalHandlerInvocationFns, IServiceProvider serviceProvider, TSignal signal, CancellationToken cancellationToken) in {SolutionDirectory}src/Conqueror/Signalling/SequentialSignalBroadcastingStrategy.cs:line FIXED","SignalTypeName":"TestSignalWithCustomSerializedPayloadType","ResponseLatency":123.456,"SignalId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":712209902,"Name":"conqueror-signal-exception"},"SourceContext":"Conqueror.Middleware.Logging.Tests.Signalling.LoggingMiddlewareTestSignals.TestSignalWithCustomSerializedPayloadType"}
