{"EventId":711195907,"LogLevel":"Information","Category":"CustomCategory_TestMessageWithoutResponseWithoutPayload","Message":"Handling message (Message ID: test-message-id, Trace ID: test-trace-id)","State":{"Message":"Handling message (Message ID: test-message-id, Trace ID: test-trace-id)","MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"Handling message (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
{"EventId":2027292319,"LogLevel":"Error","Category":"CustomCategory_TestMessageWithoutResponseWithoutPayload","Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","Exception":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages\u002BTestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayloadHandler.Handle(TestMessageWithoutResponseWithoutPayload message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload.IHandler.global::Conqueror.IMessageHandler\u003CConqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload,Conqueror.UnitMessageResponse,Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload.IHandler\u003E.Invoke(IHandler handler, TestMessageWithoutResponseWithoutPayload message, CancellationToken cancellationToken) in {ProjectDirectory}obj/Debug/net8.0/Conqueror.SourceGenerators/Conqueror.SourceGenerators.Messaging.MessageTypeGenerator/Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageWithoutResponseWithoutPayload_ConquerorMessageType.g.cs:line FIXED\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine\u0026 stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware\u00602.Execute(MessageMiddlewareContext\u00602 ctx)","State":{"Message":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","{OriginalFormat}":"An exception occurred while handling message after {ResponseLatency:0.0000}ms (Message ID: {MessageId:l}, Trace ID: {TraceId:l})"}}
