{"@t":"2020-01-01T00:00:00.0000000Z","@m":"Handling message with payload {\"Payload\":10} (Message ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","MessagePayload":"{\"Payload\":10}","MessageId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":711195907,"Name":"conqueror-message"},"SourceContext":"CustomCategory_TestMessage"}
{"@t":"2020-01-01T00:00:00.0000000Z","@m":"An exception occurred while handling message after 123.4560ms (Message ID: test-message-id, Trace ID: test-trace-id)","@i":"hash","@l":"Error","@x":"Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages+TestException: test exception\n   at Conqueror.Middleware.Logging.Tests.Messaging.LoggingMiddlewareTestMessages.TestMessageHandler.Handle(TestMessage message, CancellationToken cancellationToken) in {ProjectDirectory}Messaging/LoggingMiddlewareTestMessages.cs:line FIXED\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx) in {SolutionDirectory}src/Conqueror.Middleware.Logging/Messaging/LoggingMessageMiddleware.cs:line FIXED\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at Conqueror.Middleware.Logging.Messaging.LoggingMessageMiddleware`2.Execute(MessageMiddlewareContext`2 ctx)\n   at Conqueror.Messaging.MessagePipelineRunner`2.<>c__DisplayClass3_2.<Execute>b__1(TMessage message, CancellationToken token) in {SolutionDirectory}src/Conqueror/Messaging/MessagePipelineRunner.cs:line FIXED","ResponseLatency":123.456,"MessageId":"test-message-id","TraceId":"test-trace-id","EventId":{"Id":2027292319,"Name":"conqueror-message-exception"},"SourceContext":"CustomCategory_TestMessage"}
